name: Build Zenonia 3 VPK

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vitasdk/vitasdk:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download FalsoJNI
        run: |
          mkdir -p lib/falso_jni
          curl -sL https://github.com/SonicMastr/FalsoJNI/archive/refs/heads/master.tar.gz | tar -xz -C lib/falso_jni --strip-components=1

      - name: Build VPK
        run: |
          mkdir build && cd build
          cmake -G "Unix Makefiles" ..
          make

      - name: Upload VPK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Zenonia3-VPK
          path: |
            build/*.vpk
            build/*.bin
            build/*.self
            build/eboot.bin
